name: beamfit
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - setuptools
  - wheel
  - build
  - gcc_linux-64     # Linux
  - gcc_impl_linux-64  # Linux
  - gfortran_linux-64  # Linux (for scipy/numpy deps)
  - pytest
  - pytest-cov
  - pre-commit